spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AUCTION
    username: postgres
    password: postgres

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false